import { HeadProvider, Link, Meta, Title } from "react-head";
import { NavBar } from "../../components/common/NavBar";
import styles from "../../styles/Home.module.scss";

export default function ContactPage() {
  const navPosition = "fixed";
  return (
    <div className={styles.container}>
      <HeadProvider>
        <div className="Home">
          <Title>DnD BrussHell</Title>
          <Meta name="DnD BrussHell" content="Generated by create next app" />
          <Link rel="icon" href="/favicon.ico" />
        </div>
      </HeadProvider>
      <NavBar NavPosition={navPosition}/>
      <main className={styles.main}>
        <h1>HELLO to contact</h1>
      </main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <img src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
