import Grid from "@mui/material/Grid";
import { HeadProvider, Link, Meta, Title } from "react-head";
import CenteredSlider from "../../components/public/home/CenteredSlider";
import { DottedDivider } from "../../components/common/DottedDivider";
import { HomeIntro } from "../../components/public/home/HomeIntro";
import { NavBar } from "../../components/common/NavBar";
import PlayLeft from "../../components/public/home/PlayLeft";
import PlayRight from "../../components/public/home/PlayRight";
import TestSlider from "../../components/public/home/TestSlider";
import styles from "../../styles/Home.module.scss";

export default function HomePage() {
  const navPosition = 'top';
  return (
    <div className={styles.Home}>
      <HeadProvider>
        <div className="Home">
          <Title>DnD BrussHell</Title>
          <Meta name="DnD BrussHell" content="Generated by create next app" />
          <Link rel="icon" href="/favicon.ico" />
        </div>
      </HeadProvider>
      <NavBar NavPosition={navPosition}/>
      <main className={styles.main}>
        <div>
          <HomeIntro />
        </div>
        <div className={styles.Divider}>
          <DottedDivider />
        </div>
        <div className={styles.Slider}>
          <TestSlider />
        </div>
        <div className={styles.Divider}>
          <DottedDivider />
        </div>
        <Grid container spacing={2}>
          <Grid item xs={12}>
            <PlayRight />
          </Grid>
          <Grid item xs={12}>
            <PlayLeft />
          </Grid>
        </Grid>
        <div className={styles.Divider}>
          <DottedDivider />
        </div>
        <CenteredSlider />
      </main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <img src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
